spring.datasource.url=jdbc:postgresql://localhost:5432/yomudb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.h2.console.enabled=false

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

## To activate: --spring.profiles.active=prod
## ^^ if using PostgreSQL